version: "3.9"
services:
  db:
    image: postgres:alpine
    user: postgres
    env_file:
      - db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    networks:
      - sequencedevnetwork
  redis-server:
    image: redis:alpine
    networks:
      - sequencedevnetwork
  back:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile.back
    ports:
      - "8000:8000"
    volumes:
      - ./back:/django
    depends_on:
      - redis-server
      - db
    env_file:
      - back.env
    networks:
      - sequencedevnetwork
  front:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile.front
    ports:
      - "5000:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/coverage
      - /app/.routify
    depends_on:
      - redis-server
      - back
    env_file:
      - front.env
    networks:
      - sequencedevnetwork

networks:
  sequencedevnetwork:
    driver: bridge
    external: true
